$$$$$$$$$$$$
$$ SEARCH $$
$$$$$$$$$$$$

CREATE COLUMN TABLE SHA.SEARCH_SUBSTRINGSEARCH (
  id        INTEGER primary key,
  str       NVARCHAR(120)
);

INSERT INTO SHA.SEARCH_SUBSTRINGSEARCH VALUES (1, 'test');
INSERT INTO SHA.SEARCH_SUBSTRINGSEARCH VALUES (2, 'long test');
INSERT INTO SHA.SEARCH_SUBSTRINGSEARCH VALUES (3, 'this is a long test run');
INSERT INTO SHA.SEARCH_SUBSTRINGSEARCH VALUES (4, 'this is a long text column');
INSERT INTO SHA.SEARCH_SUBSTRINGSEARCH VALUES (5, 'this is not a result');
INSERT INTO SHA.SEARCH_SUBSTRINGSEARCH VALUES (6, 'text');
INSERT INTO SHA.SEARCH_SUBSTRINGSEARCH VALUES (7, 'long text');
INSERT INTO SHA.SEARCH_SUBSTRINGSEARCH VALUES (8, 'this result is unwanted');

SELECT * 
FROM SHA.SEARCH_SUBSTRINGSEARCH;

SELECT TO_DECIMAL(SCORE(),3,2) AS score, str 
FROM SHA.SEARCH_SUBSTRINGSEARCH 
WHERE CONTAINS(str, 'test', FUZZY(0.5, 'similarCalculationMode=SUBSTRINGSEARCH'))
ORDER BY SCORE() DESC;

CREATE COLUMN TABLE SHA.SEARCH_CWTEST (
ID INTEGER PRIMARY KEY,
txt TEXT);

INSERT INTO SHA.SEARCH_CWTEST VALUES (1, 'ManchesterUnited');
INSERT INTO SHA.SEARCH_CWTEST VALUES (2, 'Manchester United');
INSERT INTO SHA.SEARCH_CWTEST VALUES (3, 'anchesterUnited');
INSERT INTO SHA.SEARCH_CWTEST VALUES (4, 'nchesterUnited');
INSERT INTO SHA.SEARCH_CWTEST VALUES (31, 'anchester United');
INSERT INTO SHA.SEARCH_CWTEST VALUES (41, 'nchester United');
INSERT INTO SHA.SEARCH_CWTEST VALUES (5, 'Manchester');
INSERT INTO SHA.SEARCH_CWTEST VALUES (6, 'United');

SELECT *
FROM SHA.SEARCH_CWTEST;

SELECT SCORE(), *
FROM SHA.SEARCH_CWTEST
WHERE CONTAINS(txt, 'Manchester United', FUZZY(0.0, 'ts=compare'))
ORDER BY 1 DESC;

SELECT SCORE(), *
FROM SHA.SEARCH_CWTEST
WHERE CONTAINS(txt, 'Manchester United', FUZZY(0.0, 'ts=compare, composeWords=2'))
ORDER BY 1 DESC;

SELECT SCORE(), *
FROM SHA.SEARCH_CWTEST
WHERE CONTAINS(txt, 'ManchesterUnited', FUZZY(0.0, 'ts=compare'))
ORDER BY 1 DESC;

SELECT SCORE(), *
FROM SHA.SEARCH_CWTEST
WHERE CONTAINS(txt, 'ManchesterUnited', FUZZY(0.0, 'ts=compare, decomposeWords=2'))
ORDER BY 1 DESC;


CREATE COLUMN TABLE SHA.SEARCH_ETWTABLE
(
  id INTEGER PRIMARY KEY,
  t  TEXT    FUZZY SEARCH INDEX ON
);

INSERT INTO SHA.SEARCH_ETWTABLE VALUES (1,'Pink Floyd');
INSERT INTO SHA.SEARCH_ETWTABLE VALUES (2,'Pink Floyd and Syd Barratt');
INSERT INTO SHA.SEARCH_ETWTABLE VALUES (3,'Piper at the Gates of Dawn (Pink Floyd)');
INSERT INTO SHA.SEARCH_ETWTABLE VALUES (4,'Kinp Dylof');

-- select 1
SELECT TO_DECIMAL(SCORE(),3,2) AS score, * FROM SHA.SEARCH_ETWTABLE
WHERE CONTAINS(t, 'Pink Floyd', FUZZY(0.5,'textSearch=compare,excessTokenWeight=1.0'))
ORDER BY score DESC, id;

-- select 2
SELECT TO_DECIMAL(SCORE(),3,2) AS score, * FROM SHA.SEARCH_ETWTABLE
WHERE CONTAINS(t, 'Pink Floyd', FUZZY(0.5,'textSearch=compare,excessTokenWeight=0.1'))
ORDER BY score DESC, id;

-- select 2b
SELECT TO_DECIMAL(SCORE(),3,2) AS score, * FROM SHA.SEARCH_ETWTABLE
WHERE CONTAINS(t, 'Pink Floyd', FUZZY(0.5,'textSearch=compare,excessTokenWeight=0.0'))
ORDER BY score DESC, id;

$$$$$$$$$$$$$$$$$$$
$$ TEXT ANALYSIS $$
$$$$$$$$$$$$$$$$$$$

select * from SYS.M_TEXT_ANALYSIS_LANGUAGES;

DROP TABLE SHA.TEXTANALYSIS_DATA;
CREATE COLUMN TABLE SHA.TEXTANALYSIS_DATA
(
ID INTEGER PRIMARY KEY, 
STRING nvarchar(200)
)
;

INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (1, 'Bob really likes Manchester United.');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (2, 'Bob hasst den FC Bayern München.');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (3, 'ボブは  東京  を楽しんで');

DROP FULLTEXT INDEX SHA.TEXTANALYSIS_INDEX;
CREATE FULLTEXT INDEX TEXTANALYSIS_INDEX ON SHA.TEXTANALYSIS_DATA ("STRING")
LANGUAGE DETECTION ('EN')
-- LANGUAGE DETECTION ('DE')
-- LANGUAGE DETECTION ('EN','DE')
-- LANGUAGE DETECTION ('ZH')
CONFIGURATION 'EXTRACTION_CORE_VOICEOFCUSTOMER'
TEXT ANALYSIS ON;

SELECT * FROM "SHA"."$TA_TEXTANALYSIS_INDEX";

INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (4, 'I am tremendously happy with my purchase.');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (5, 'I am not tremendously happy with my purchase.');

DROP FULLTEXT INDEX SHA.TEXTANALYSIS_INDEX;
CREATE FULLTEXT INDEX TEXTANALYSIS_INDEX ON SHA.TEXTANALYSIS_DATA ("STRING")
CONFIGURATION 'EXTRACTION_CORE_VOICEOFCUSTOMER'
TEXT ANALYSIS ON;

SELECT * FROM "SHA"."$TA_TEXTANALYSIS_INDEX" 
WHERE ID IN (4,5) 
AND TA_TYPE LIKE '%eSentiment';

INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (6, 'Tahir Hussain Babar, aka Bob, is a SAP employee.');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (7, 'Bob is a large 6 ft tall English man.');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (8, 'Bob travelled to Dublin, CA.');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (9, 'Bob is 35 miles east of San Francisco.');

DROP FULLTEXT INDEX SHA.TEXTANALYSIS_INDEX;
CREATE FULLTEXT INDEX TEXTANALYSIS_INDEX ON SHA.TEXTANALYSIS_DATA ("STRING")
CONFIGURATION 'EXTRACTION_CORE_PUBLIC_SECTOR'
TEXT ANALYSIS ON;

SELECT * FROM "SHA"."$TA_TEXTANALYSIS_INDEX" WHERE ID in (6,7,8,9) ;

INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (10, 'Bernard Liautaud co-founded Business Objects in 1990.');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (11, 'Business Objects introduces WebI thin client in 1997');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (12, 'SAP AG announced that it would acquire Business Objects for $6.8B in 2007.');
INSERT INTO SHA.TEXTANALYSIS_DATA VALUES (13, 'SAP AG releases SAP HANA SPS10 in 2015.');

DROP FULLTEXT INDEX SHA.TEXTANALYSIS_INDEX;
CREATE FULLTEXT INDEX TEXTANALYSIS_INDEX ON SHA.TEXTANALYSIS_DATA ("STRING")
CONFIGURATION 'EXTRACTION_CORE_ENTERPRISE'
TEXT ANALYSIS ON;

SELECT * FROM "SHA"."$TA_TEXTANALYSIS_INDEX" WHERE ID > 9;
