--------------------------------------
--
-- start with creating a series table
--
--------------------------------------

DROP TABLE SERIES_DATA.WEATHER_HOURLY;
CREATE COLUMN TABLE SERIES_DATA.WEATHER_HOURLY (
	SENSOR VARCHAR(15), 
	TIMER TIMESTAMP, 
	TMP DECIMAL(10,2),
	DWP DECIMAL(10,2)
)
SERIES (
	SERIES KEY(SENSOR) 
	PERIOD FOR SERIES(TIMER)
	EQUIDISTANT INCREMENT BY INTERVAL 1 HOUR
	MINVALUE '2013-01-01 00:00:00'
	MAXVALUE '2014-12-31 23:00:00'
 );


INSERT INTO SERIES_DATA.WEATHER_HOURLY (
	SELECT SENSOR, TIMER, AVG(TMP), AVG(DWP) 
	FROM (
		SELECT "station" AS SENSOR, SERIES_ROUND(TO_TIMESTAMP ("valid(UTC)", 'YYYY-MM-DD HH24:MI'), 'INTERVAL 1 HOUR', ROUND_DOWN) AS TIMER, "tmpf" AS TMP, "dwpf" AS DWP 
		FROM SERIES_DATA.WEATHER_ORIG
	)
	GROUP BY TIMER, SENSOR
);

-- select statement from weather table is standard sql

SELECT * FROM SERIES_DATA.WEATHER_HOURLY;

-- select generated series info

SELECT *
FROM SERIES_GENERATE_TIMESTAMP (
 	SERIES TABLE SERIES_DATA.WEATHER_HOURLY
) W;
