############
## SEARCH ##
############

DROP TABLE SEARCH_SUBSTRINGSEARCH;
CREATE COLUMN TABLE SEARCH_SUBSTRINGSEARCH (
  id        INTEGER primary key,
  str       NVARCHAR(120)
);

INSERT INTO SEARCH_SUBSTRINGSEARCH VALUES (1, 'test');
INSERT INTO SEARCH_SUBSTRINGSEARCH VALUES (2, 'long test');
INSERT INTO SEARCH_SUBSTRINGSEARCH VALUES (3, 'this is a long test run');
INSERT INTO SEARCH_SUBSTRINGSEARCH VALUES (4, 'this is a long text column');
INSERT INTO SEARCH_SUBSTRINGSEARCH VALUES (5, 'this is not a result');
INSERT INTO SEARCH_SUBSTRINGSEARCH VALUES (6, 'text');
INSERT INTO SEARCH_SUBSTRINGSEARCH VALUES (7, 'long text');
INSERT INTO SEARCH_SUBSTRINGSEARCH VALUES (8, 'this result is unwanted');

SELECT * 
FROM SEARCH_SUBSTRINGSEARCH; 

SELECT TO_DECIMAL(SCORE(),3,2) AS score, str 
FROM SEARCH_SUBSTRINGSEARCH 
WHERE CONTAINS(str, 'test', FUZZY(0.5, 'similarCalculationMode=SUBSTRINGSEARCH'))
ORDER BY SCORE() DESC;

DROP TABLE SEARCH_CWTEST;
CREATE COLUMN TABLE SEARCH_CWTEST (
ID INTEGER PRIMARY KEY,
txt TEXT);

INSERT INTO SEARCH_CWTEST VALUES (1, 'ManchesterUnited');
INSERT INTO SEARCH_CWTEST VALUES (2, 'Manchester United');
INSERT INTO SEARCH_CWTEST VALUES (3, 'anchesterUnited');
INSERT INTO SEARCH_CWTEST VALUES (4, 'nchesterUnited');
INSERT INTO SEARCH_CWTEST VALUES (31, 'anchester United');
INSERT INTO SEARCH_CWTEST VALUES (41, 'nchester United');
INSERT INTO SEARCH_CWTEST VALUES (5, 'Manchester');
INSERT INTO SEARCH_CWTEST VALUES (6, 'United');

SELECT *
FROM SEARCH_CWTEST;

SELECT SCORE(), *
FROM SEARCH_CWTEST
WHERE CONTAINS(txt, 'Manchester United', FUZZY(0.0, 'ts=compare'))
ORDER BY 1 DESC;

SELECT SCORE(), *
FROM SEARCH_CWTEST
WHERE CONTAINS(txt, 'Manchester United', FUZZY(0.0, 'ts=compare, composeWords=2'))
ORDER BY 1 DESC;

SELECT SCORE(), *
FROM SEARCH_CWTEST
WHERE CONTAINS(txt, 'ManchesterUnited', FUZZY(0.0, 'ts=compare'))
ORDER BY 1 DESC;

SELECT SCORE(), *
FROM SEARCH_CWTEST
WHERE CONTAINS(txt, 'ManchesterUnited', FUZZY(0.0, 'ts=compare, decomposeWords=2'))
ORDER BY 1 DESC;

DROP TABLE SEARCH_ETWTABLE;
CREATE COLUMN TABLE SEARCH_ETWTABLE
(
  id INTEGER PRIMARY KEY,
  t  TEXT    FUZZY SEARCH INDEX ON
);

INSERT INTO SEARCH_ETWTABLE VALUES (1,'Pink Floyd');
INSERT INTO SEARCH_ETWTABLE VALUES (2,'Pink Floyd and Syd Barratt');
INSERT INTO SEARCH_ETWTABLE VALUES (3,'Piper at the Gates of Dawn (Pink Floyd)');
INSERT INTO SEARCH_ETWTABLE VALUES (4,'Kinp Dylof');

-- select 1
SELECT TO_DECIMAL(SCORE(),3,2) AS score, * FROM SEARCH_ETWTABLE
WHERE CONTAINS(t, 'Pink Floyd', FUZZY(0.5,'textSearch=compare,excessTokenWeight=1.0'))
ORDER BY score DESC, id;

-- select 2
SELECT TO_DECIMAL(SCORE(),3,2) AS score, * FROM SEARCH_ETWTABLE
WHERE CONTAINS(t, 'Pink Floyd', FUZZY(0.5,'textSearch=compare,excessTokenWeight=0.1'))
ORDER BY score DESC, id;

-- select 2b
SELECT TO_DECIMAL(SCORE(),3,2) AS score, * FROM SEARCH_ETWTABLE
WHERE CONTAINS(t, 'Pink Floyd', FUZZY(0.5,'textSearch=compare,excessTokenWeight=0.0'))
ORDER BY score DESC, id;
